### ISSUE TITLE
Generate API keys doc outdated

### ISSUE THREAD

**Issue by stephenmathieson** [DrewML/chrome-webstore-upload#19]
I've just begun my adventure into automating publishing an extension to the Chrome store. I found this package and was super excited about how simple it should make this process.

However, when attempting to follow the "_How to generate Google API keys_" doc, I ran into the following error:

<img width="1041" alt="API solution not found with service name: chromewebstore" src="https://user-images.githubusercontent.com/571265/46214758-c90d1580-c309-11e8-9715-e1b56f8e1b90.png">

_ALT - API solution not found with service name: chromewebstore_

Have you seen this? Is the doc outdated, or have I done something wrong on my end?

Thanks!

**Comment by antibot4navalny** [comment]
This official guide from Google helped me to workaround the outdated doc on requesting access / refresh tokens:
https://developer.chrome.com/webstore/using_webstore_api#beforeyoubegin

**Comment by fwextensions** [comment]
Even the official Google guide seems to be out-of-date now.  It says:

> In the sidebar on the left, select APIs & auth.
> In the displayed list of available APIs, set the status of the Chrome Web Store API to ON.

There's no "APIs & auth" on the left.  You have to click *Library* and then search for `store`, which will bring up the Chrome Web Store API.  Then click that API and click *Enable*, rather than *ON*, on the next page.

Even with that fixed, I'm still getting `'Response code 400 (Bad Request)'` when trying to publish.
