### ISSUE TITLE
Getting a 404 on publish

### ISSUE THREAD

**Issue by EliRobinson** [DrewML/chrome-webstore-upload#20]
Getting this when I try to publish:

`Error while publishing uploaded extension: HTTPError: Response code 404 (Not Found)`

Refreshed my refresh token and still no luck. Any thoughts?

**Comment by bfred-it** [comment]
Make sure that the extension ID is correct. If the API returns 404, the URL isn't right. But if the URL wasn't right then it wouldn't work for anyone.

Since the extension ID is the only part of the URL that changes, that's what's causing the 404:

https://github.com/DrewML/chrome-webstore-upload/blob/2622ab4f7a8c525ac51eb61a65fb7f7593934fdc/index.js#L4-L8
