### ISSUE TITLE
Publish error "Publish condition not met: "

### ISSUE THREAD

**Issue by enertom** [DrewML/chrome-webstore-upload#22]
I have an error after upload an extension: {"error":{"errors":[{"domain":"global","reason":"badRequest","message":"Publish condition not met: "}],"code":400,"message":"Publish condition not met: "}}

**Comment by bfred-it** [comment]
This isn't due to the module, sadly the error doesn't specify what the issue is exactly. Probably your extension isn't public or not accepted or wrong.

You can only google it: https://www.google.com/search?q=%22Publish+condition+not+met

**Comment by joelpurra** [comment]
Searching for the error message got me here ;)

@enertom: got the same empty explanation -- it is indeed not a problem with chrome-webstore-upload. A proper explanation showed up trying to manually publish the extension from the chrome web store developer dashboard. I have a paid extension, and it turns out not all Google Payments Merchant Center account setup steps had been performed -- needed to add and verify a payment method first.

**Comment by bfred-it** [comment]
Also: https://github.com/DrewML/chrome-webstore-upload/issues/25
